apiVersion: extensions/v1beta1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: "{{ .Release.Name }}"
=======
  name: "{{ .Chart.Name }}-{{ .Values.buildNumber}}"
>>>>>>> master
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    env: "{{ .Values.environment }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        env: "{{ .Values.environment }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.account }}/{{ .Chart.Name }}-{{ .Values.branch }}:{{ .Values.buildNumber }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
